# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: MacOS X Native Image

on:
  push:
    branches: [ binary ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install GraalVM Native Image
        shell: bash
        run: ./graalvm-mac.sh
      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Jar
        run: ./gradlew build
      - name: Build Binary
        shell: bash
        run: ./native.sh

